#!/bin/bash

# bspwm-specific autostart

bspc config top_padding			30
bspc config border_width 		4
bspc config window_gap 			0
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config initial_polarity second_child
bspc config split_ratio 0.6180339903912632
bspc config focus_by_distance   true

bspc config auto_cancel 		true

bspc monitor -d 1 2 3 4

export _JAVA_AWT_WM_NONREPARENTING=1

compton --frame-opacity 0.5 &

xfsettingsd &
xfdesktop --disable-wm-check &
xfce4-panel --disable-wm-check &
xfce4-notifyd &

dex -a &
thunar --daemon &
chromium --no-startup-window &
