#!/bin/bash

# bspwm-specific autostart

panel_height=28
window_gap=4

if [[ "$(hostname)" == "tinfoil" ]]; then
    primary_monitor=eDP1
    secondary_monitor=HDMI2

elif [[ "$(hostname)" == "tinbox" ]]; then
    # Discrete graphics
    primary_monitor=DisplayPort-0
    secondary_monitor=HDMI-A-0

    # Integrated graphics
    # primary_monitor=DP2
    # secondary_monitor=HDMI1
fi

bspc config pointer_modifier mod4

bspc config border_width 0
bspc config window_gap $window_gap
bspc config -m $primary_monitor top_padding $((panel_height - window_gap))
bspc config -m $secondary_monitor top_padding -$window_gap
bspc config bottom_padding -$window_gap
bspc config left_padding -$window_gap
bspc config right_padding -$window_gap
bspc config presel_feedback_color '#1B2B34' 
bspc config focus_follows_pointer true

bspc config initial_polarity second_child

bspc monitor $primary_monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor $secondary_monitor -d ext

# bspc config remove_unplugged_monitors true
# bspc config remove_disabled_monitors true

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Polybar border=off
bspc rule -a Gtkwave state=tiled
bspc rule -a "Org.gnome.Weather.Application" state=floating
bspc rule -a "Gpick" state=floating
bspc rule -a "GLava" state=floating layer=below sticky=true locked=true border=off rectangle=2560x1600+0+0
bspc rule -a Pavucontrol state=floating
bspc rule -a UE4Editor desktop=^2
bspc rule -a discord desktop=^10
bspc rule -a Zenity focus=off

"$HOME"/.config/bspwm/startup.sh &
