#!/bin/bash

# bspwm-specific autostart

bspc config click_to_focus		true
bspc config pointer_modifier mod1

bspc config top_padding			44
bspc config border_width 		4
bspc config window_gap 			0

bspc config presel_feedback_color '#1B2B34' 
bspc config auto_cancel 		true

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

bspc config initial_polarity second_child
bspc monitor -d 0 0 0 0 0 0 0

bspc rule -a Zathura state=tiled

$HOME/.config/bspwm/startup.sh &
