#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config auto_alternate              false
bspc config auto_cancel                 true

bspc config border_width                2
bspc config window_gap                  80
bspc config normal_border_color         "#c6c6c6"
bspc config focused_border_color        "#87af87"
bspc config presel_border_color         "#875fff"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

bspc rule -a Graphics floating=on center=on

panel &
