#!/bin/sh
desc_color=4

while read -r line; do
	data="${line#??}"
	case "$line" in
		WM*)
			wminfo=""
			IFS=':'
			set -- $data
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in 
					m*)
						# ignore unfocused monitor's desktop
						shift
						;;
					u*)
						# urgent desktop
						wminfo="$wminfo\\u3   ${name}   \\ur"
						;;
				[DU]*)
						# active desktop (may be urgent too)
						wminfo="$wminfo\\u7   ${name}   \\ur"
						;;
					d*)
						# inactive but occupied desktop
						wminfo="$wminfo   ${name}   "
						;;
					E*)
						# empty, inactive desktop
						wminfo="$wminfo\\f7   ${name}   \\fr"
						;;
					esac
					shift
				done
			;;
		CP*)
			cpu="\\f${desc_color}Cpu\\fr $data\%"
			#if [[ "$data" -gt 22 ]]; then
			#    cpu="\\u3$cpu\\ur"
			#fi
			;;
		ME*)
			memory="\\f${desc_color}Mem\\fr $data"
			;;
		#UP*)
			#upspeed="\\f${desc_color}Up\\fr $data"
			#;;
		#DW*)
			#downspeed="\\f${desc_color}Down\\fr $data"
			#;;
		BA*)
			battery="\\f${desc_color}Batt\\fr $data\%"
			if [[ "$data" -le 10 ]]; then
				battery="\\u3$battery\\ur"
			fi
			;;
		BT*)
			battery_time="\\f7[\\fr$(echo "$data" | cut -d\  -f1-2)\\f7]\\fr"
			;;
		TE*)
			temperature="\\f${desc_color}Temp\\fr $data°C"
			;;
		DA*)
			mydate="\\f${desc_color}Date\\fr $data"
			;;
		TI*)
			mytime="\\f${desc_color}Time\\fr $data"
			;;
	esac

	printf '\\l%s\\r%s  %s  %s  %s %s  %s  %s\n' "$wminfo" "$cpu" "$memory" "$temperature" "$battery" "$battery_time" "$mydate" "$mytime"
done
