font_family Fira Mono Medium
bold_font Fira Mono Bold
bold_italic_font Fira Mono Bold
italic_font Fira Mono Medium
font_size 9
adjust_line_height 114%

# Saves about 10ms in input latency
sync_to_monitor no 

# Saves about 1ms in input latency (sometimes? only when bold fonts aren't enabled?)
# Causes screen tearing though
# input_delay 0 

# Doesn't seem to save any latency
# repaint_delay 0 

enable_audio_bell no

allow_remote_control yes

# Dracula theme
background #1e1f28
foreground #f8f8f2
cursor #bbbbbb
selection_background #44475a
color0 #000000
color8 #545454
color1 #ff5555
color9 #ff5454
color2 #50fa7b
color10 #50fa7b
color3 #f0fa8b
color11 #f0fa8b
color4 #bd92f8
color12 #bd92f8
color5 #ff78c5
color13 #ff78c5
color6 #8ae9fc
color14 #8ae9fc
color7 #bbbbbb
color15 #ffffff
selection_foreground #1e1f28

# vim:ft=toml
